### ISSUE TITLE
Cookbook has disappeared 

### ISSUE THREAD

**Issue by cthoyt** [biojava/biojava.github.io#11]
The cookbook is currently missing... The only way to look up tutorials is through google searches and cached pages

**Comment by andreasprlic** [comment]
unfortunately we had to do an emergency migration of the old website. In the process of this the cookbook got moved here: http://biojava.org/wiki.html . However it is not well structured and many links don't work. As such @rmoszczynski is working on moving it to a GitHub wiki. See #10

**Comment by rmoszczynski** [comment]
@cthoyt here is a direct link to the fork I'm working on: https://github.com/rmoszczynski/biojava/wiki

**Comment by rmoszczynski** [comment]
@cthoyt you can tell me what information you are looking for so I can prioritize it first.

**Comment by cthoyt** [comment]
It would be really nice to have a recipe for retrieving FASTA files by Uniprot and HGNC identifiers, and working with the sequence alignment packages

**Comment by rmoszczynski** [comment]
Ok, thank you. I will do it first.

**Comment by rmoszczynski** [comment]
Here is what you are looking for: http://biojava.org/wiki/BioJava%3ACookbook%3ASeqIO%3AGBtoFasta

I have not migrated the recipe to the wiki because we want to put the cookbook recipes not to the wiki but to a separate repo https://github.com/biojava/biojava-cookbook. I'm working on the technical concept of the cookbook and will start to migrate probably after New Year.

**Comment by andreasprlic** [comment]
actually that's an entry for BioJava 1 ...

**Comment by sbliven** [comment]
We should at least make http://biojava.org/wiki/BioJava:CookBook4.0 give a reasonable page, for backwards compatibility. This currently seems to have two problems:
- The `:` needs to be escaped to `%3A` to get Jekyll to find it
- The `.0` is recognized by Jekyll as an extension and delivered with content-type application/octet-stream

**Comment by sbliven** [comment]
Adding / to the end of the permlink seems to fix both problems.
