### ISSUE TITLE
Enable HTTPS for website

### ISSUE THREAD

**Issue by hlapp** [biojava/biojava.github.io#15]
Through a partnership with Let's Encrypt [Github allows HTTPS for custom domains since May 1](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/). I suggest enabling this here.

You might need to trigger SSL cert issuance, see bioperl/bioperl.github.io#45.

**Comment by hlapp** [comment]
Correct DNS settings are now in place.

**Comment by josemduarte** [comment]
Thanks @hlapp! I'll look into this as soon as possible

**Comment by hlapp** [comment]
@josemduarte any update? I'm going to mention this at BOSC 2018 just after lunch, and Biojava is one of the two ones lagging behind. (Bioruby being the other one.)

**Comment by josemduarte** [comment]
Sorry for not getting back before. I did try some changes a few weeks ago but didn't have more time to look into it. Right now I've tried and https://biojava.org works just fine. I've just switched the default to https in github pages settings.

Thanks for the help @hlapp !

**Comment by hlapp** [comment]
Awesome, thanks @josemduarte for the prompt attention! Yay!
