### ISSUE TITLE
Using "www" subdomain in website

### ISSUE THREAD

**Issue by lafita** [biojava/biojava.github.io#17]
I have been reviewing some of the literature citing BioJava and most articles link to the URL www.biojava.org 

This URL is currently not available, because of the `www` subdomain. 
Would it be possible to redirect this URL to the https://biojava.org website?

**Comment by sbliven** [comment]
I'll report this to OBF. They're maintaining the DNS records. It should just work from the github side.

**Comment by sbliven** [comment]
Should be fixed now. Thanks  @hlapp!

**Comment by lafita** [comment]
Thanks @sbliven and @hlapp! 🎉😄
