### ISSUE TITLE
Broken project website

### ISSUE THREAD

**Issue by rmoszczynski** [biojava/biojava.github.io#7]
The biojava website is really broken. I found blind text for example on the page http://biojava.org/generic.html.

By the way there are pages linked in the main menu like http://biojava.org/404.html (with a redirect loop) or http://biojava.org/elements.html showing possible website elements not containing project relevant content.

In my opinion the project needs a new website. If you see it that way I could build a new one. Please let me know.

**Comment by andreasprlic** [comment]
Hi Robert,

we recently had to do an emergency migration from our old hosting to github pages. 

The Generic and "elements" pages you found are examples how to create a page in the new template. 

I don't think we should change away from Github pages, however the organisation of the site needs a lot of improvements. Any pull requests for improvements to the site are welcome!


Andreas

**Comment by rmoszczynski** [comment]
I also don't think we should change away from GitHub pages. What I auggest is to polish the website to a modern responsive design and leave only production ready content. We can link a lot of examples on a wiki page about it.

It is also relevant for this topic to move the wiki away for example to a GitHub wiki. I don't think the website itself is a good place for a project wiki. What do you think?

Can I propose some improvements to the website?

**Comment by sbliven** [comment]
In #12 I fix the menu problems you mention. Let's close this issue, with the understanding that we will still have a major website update after the wiki pages get migrated into the cookbook or tutorial projects.
