### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by rmoszczynski** [biojava/biojava.github.io#9]
If we talk about the possibility of a new website, maybe it is time for a new logo? It is nice but maybe we can get something fresh?

What do you think?

**Comment by andreasprlic** [comment]
we just recently held a logo redesign competition. https://github.com/biojava/logo

The version on the website perhaps needs a higher resolution, or perhaps we could use an svg version, so it looks less pixelated...?

**Comment by rmoszczynski** [comment]
Ah, OK this is also the new logo. Unfortunately, I am too late to propose one.
